SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\STC
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=STC15F408AD
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"C:\Keil_v5\C51\BIN\C51.EXE" @"INTERR~1.__I"
"C:\Keil_v5\C51\BIN\C51.EXE" @"main.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"delay.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"uart.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"NFR24L01.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"OLED12~1.__I"
"C:\Keil_v5\C51\BIN\C51.EXE" @"oledcode.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"KEY_FI~1.__I"
"C:\Keil_v5\C51\BIN\BL51.EXE" @"STC15~1.LNP"
"C:\Keil_v5\C51\BIN\OH51.EXE" "stc15≤‚ ‘" 
